name: wxread

on:
  schedule:
    - cron: '0 15 * * *'  # 北京时间 23:00（UTC 时间 15:00）
    - cron: '0 19 * * *'  # 北京时间 3:00（UTC 时间 19:00）
    - cron: '0 9 * * *'   # 北京时间 17:00（UTC 时间 9:00）
  workflow_dispatch:      # 手动触发

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: AutoRead  # 指定环境

    steps:

    - name: Set DNS to Google's DNS
      run: |
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install certifi==2024.8.30 charset-normalizer==3.4.0 idna==3.10 requests==2.32.3 urllib3==2.2.3

    - name: Random delay between 0-10 minutes
      run: |
        DELAY=$((RANDOM % 11)) # 生成 0 到 10 分钟的随机延迟
        echo "Delaying for $DELAY minutes..."
        sleep $((DELAY * 60)) # 转换为秒并等待

    - name: Generate random READ_NUM
      run: |
        RANDOM_NUM=$((RANDOM % 61 + 120)) # 生成 120 到 180 分钟（2-3 小时）
        echo "READ_NUM=$RANDOM_NUM" >> $GITHUB_ENV
        echo "Running for $RANDOM_NUM minutes"

    - name: Run deployment script
      env:
        WXREAD_CURL_BASH: ${{ secrets.WXREAD_CURL_BASH }}
        PUSH_METHOD: ${{ secrets.PUSH_METHOD }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        WXPUSHER_SPT: ${{ secrets.WXPUSHER_SPT }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        READ_NUM: ${{ env.READ_NUM }}  # 使用随机生成的 READ_NUM
      run: |
        python main.py
